/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createDeliveryBoxPartsInfoModelFromDiscriminatorValue, serializeDeliveryBoxPartsInfoModel, type DeliveryBoxPartsInfoModel } from '../models/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeliveryBoxPartsInfo
 */
export interface DeliveryBoxPartsInfoRequestBuilder extends BaseRequestBuilder<DeliveryBoxPartsInfoRequestBuilder> {
    /**
     * Get all Delivery Box Parts Info
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of DeliveryBoxPartsInfoModel
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<DeliveryBoxPartsInfoModel[] | undefined>;
    /**
     * Create a new
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     post(body: DeliveryBoxPartsInfoModel, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Get all Delivery Box Parts Info
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Create a new
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toPostRequestInformation(body: DeliveryBoxPartsInfoModel, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Metadata for all the requests in the request builder.
 */
export const DeliveryBoxPartsInfoRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollectionAsync",
        responseBodyFactory:  createDeliveryBoxPartsInfoModelFromDiscriminatorValue,
    },
    post: {
        adapterMethodName: "sendNoResponseContentAsync",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeDeliveryBoxPartsInfoModel,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/**
 * Uri template for the request builder.
 */
export const DeliveryBoxPartsInfoRequestBuilderUriTemplate = "{+baseurl}/DeliveryBoxPartsInfo";
/* tslint:enable */
/* eslint-enable */
