/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createFilamentModelFromDiscriminatorValue, serializeFilamentModel, type FilamentModel } from '../models/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /filament?id={id}
 */
export interface FilamentWithIdRequestBuilder extends BaseRequestBuilder<FilamentWithIdRequestBuilder> {
    /**
     * Delete by ID
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<FilamentWithIdRequestBuilderDeleteQueryParameters> | undefined) : Promise<void>;
    /**
     * Get by ID
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of FilamentModel
     */
     get(requestConfiguration?: RequestConfiguration<FilamentWithIdRequestBuilderGetQueryParameters> | undefined) : Promise<FilamentModel | undefined>;
    /**
     * Update by ID
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of ArrayBuffer
     */
     put(body: FilamentModel, requestConfiguration?: RequestConfiguration<FilamentWithIdRequestBuilderPutQueryParameters> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * Delete by ID
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<FilamentWithIdRequestBuilderDeleteQueryParameters> | undefined) : RequestInformation;
    /**
     * Get by ID
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<FilamentWithIdRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Update by ID
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toPutRequestInformation(body: FilamentModel, requestConfiguration?: RequestConfiguration<FilamentWithIdRequestBuilderPutQueryParameters> | undefined) : RequestInformation;
}
/**
 * Delete by ID
 */
export interface FilamentWithIdRequestBuilderDeleteQueryParameters {
    id?: string;
}
/**
 * Get by ID
 */
export interface FilamentWithIdRequestBuilderGetQueryParameters {
    id?: string;
}
/**
 * Update by ID
 */
export interface FilamentWithIdRequestBuilderPutQueryParameters {
    id?: string;
}
/**
 * Metadata for all the requests in the request builder.
 */
export const FilamentWithIdRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        adapterMethodName: "sendNoResponseContentAsync",
    },
    get: {
        responseBodyContentType: "application/json",
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createFilamentModelFromDiscriminatorValue,
    },
    put: {
        adapterMethodName: "sendPrimitiveAsync",
        responseBodyFactory:  "ArrayBuffer",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeFilamentModel,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/**
 * Uri template for the request builder.
 */
export const FilamentWithIdRequestBuilderUriTemplate = "{+baseurl}/filament?id={id}?id={id}";
/* tslint:enable */
/* eslint-enable */
