/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createPartItemModelFromDiscriminatorValue, serializePartItemModel, type PartItemModel } from '../models/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /PartItem
 */
export interface PartItemRequestBuilder extends BaseRequestBuilder<PartItemRequestBuilder> {
    /**
     * Get all
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of PartItemModel
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PartItemModel[] | undefined>;
    /**
     * Create a new
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     post(body: PartItemModel, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Get all
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Create a new
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toPostRequestInformation(body: PartItemModel, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Metadata for all the requests in the request builder.
 */
export const PartItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollectionAsync",
        responseBodyFactory:  createPartItemModelFromDiscriminatorValue,
    },
    post: {
        adapterMethodName: "sendNoResponseContentAsync",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializePartItemModel,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/**
 * Uri template for the request builder.
 */
export const PartItemRequestBuilderUriTemplate = "{+baseurl}/PartItem";
/* tslint:enable */
/* eslint-enable */
