/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createDeliveryBoxPartsInfoModelFromDiscriminatorValue, serializeDeliveryBoxPartsInfoModel, type DeliveryBoxPartsInfoModel } from '../models/';
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /DeliveryBoxPartsInfo?id={id}
 */
export interface DeliveryBoxPartsInfoWithIdRequestBuilder extends BaseRequestBuilder<DeliveryBoxPartsInfoWithIdRequestBuilder> {
    /**
     * Delete by ID
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of ArrayBuffer
     */
     delete(requestConfiguration?: RequestConfiguration<DeliveryBoxPartsInfoWithIdRequestBuilderDeleteQueryParameters> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * Get by ID
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of DeliveryBoxPartsInfoModel
     */
     get(requestConfiguration?: RequestConfiguration<DeliveryBoxPartsInfoWithIdRequestBuilderGetQueryParameters> | undefined) : Promise<DeliveryBoxPartsInfoModel | undefined>;
    /**
     * Update by ID
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of ArrayBuffer
     */
     put(body: DeliveryBoxPartsInfoModel, requestConfiguration?: RequestConfiguration<DeliveryBoxPartsInfoWithIdRequestBuilderPutQueryParameters> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * Delete by ID
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<DeliveryBoxPartsInfoWithIdRequestBuilderDeleteQueryParameters> | undefined) : RequestInformation;
    /**
     * Get by ID
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<DeliveryBoxPartsInfoWithIdRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * Update by ID
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
     toPutRequestInformation(body: DeliveryBoxPartsInfoModel, requestConfiguration?: RequestConfiguration<DeliveryBoxPartsInfoWithIdRequestBuilderPutQueryParameters> | undefined) : RequestInformation;
}
/**
 * Delete by ID
 */
export interface DeliveryBoxPartsInfoWithIdRequestBuilderDeleteQueryParameters {
    id?: string;
}
/**
 * Get by ID
 */
export interface DeliveryBoxPartsInfoWithIdRequestBuilderGetQueryParameters {
    id?: string;
}
/**
 * Update by ID
 */
export interface DeliveryBoxPartsInfoWithIdRequestBuilderPutQueryParameters {
    id?: string;
}
/**
 * Metadata for all the requests in the request builder.
 */
export const DeliveryBoxPartsInfoWithIdRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        adapterMethodName: "sendPrimitiveAsync",
        responseBodyFactory:  "ArrayBuffer",
    },
    get: {
        responseBodyContentType: "application/json",
        adapterMethodName: "sendAsync",
        responseBodyFactory:  createDeliveryBoxPartsInfoModelFromDiscriminatorValue,
    },
    put: {
        adapterMethodName: "sendPrimitiveAsync",
        responseBodyFactory:  "ArrayBuffer",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeDeliveryBoxPartsInfoModel,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/**
 * Uri template for the request builder.
 */
export const DeliveryBoxPartsInfoWithIdRequestBuilderUriTemplate = "{+baseurl}/DeliveryBoxPartsInfo?id={id}?id={id}";
/* tslint:enable */
/* eslint-enable */
